### ISSUE TITLE
Add script to construct web annotations from per-page language detection

### ISSUE THREAD

**Issue by proycon** [brambg/globalise-tools#8]
The output of the automatic language detection pipeline (knaw-huc/team-text-backlog#65) will be a TSV file with columns (amongst others!):

`inv_nr  page_no    langs`

langs is a comma separated list of iso-639-3 language codes representing the languages that were found on the page.

This information needs to be translated to Web Annotations so people can search for languages in TextAnnoViz.

In addition to the automated output, there will be a similar TSV file with manually curated results, if a inv_nr and page_no occurs in there, it should override/ignore whatever is in the automated output's TSV.

I'll post a comment with links to the actual TSV files once they are ready.

@brambg: You have most expertise with the web annotation output and feeling for how that integrates into AnnoRepo/Broccoli/ TextAnnoViz . I could also give it a try, but perhaps this is something you can pick up?

@kintopp: Thus far this addresses only the page results, do we also want to propagate the paragraph or even line results (noisy!) to the rest of the system?

**Comment by brambg** [comment]
Re: web annotations: I can incorporate the lang information as an extra `body.metadata.lang` field in the `Page` annotations in the `gt-untangle-globalise` script: 
https://github.com/knaw-huc/globalise-tools/blob/main/scripts/gt-untangle-globalise.py

**Comment by proycon** [comment]
That looks good to me yeah, with multiple lang properties if there are multiple languages I assume?

**Comment by brambg** [comment]
Yes, I'll make it a a list:

`"lang": [ "nl", "de", "la"]`

**Comment by proycon** [comment]
I forgot to provide further feedback: 

The pipeline output (`pages.lang.tsv`) is published in https://github.com/globalise-huygens/language-identification-data/tree/main/latin-script-pages . The manual corrected output should override whatever is in `pages.lang.tsv` and is still pending (@kintopp )

**Comment by proycon** [comment]
> Yes, I'll make it a a list:
> 
> `"lang": [ "nl", "de", "la"]`

Right, you'll get iso-639-3 from the pipeline, I think @kintopp prefers that for the final web annotations too.

**Comment by proycon** [comment]
Another small update: The pipeline output (`pages.lang.tsv`) published in https://github.com/globalise-huygens/language-identification-data/tree/main/latin-script-pages now already includes all manually curated output as well. There's a column `corrected` with values `0` or `1` indicating if the entry is the result of a manual correction or not. You can propagate that information to the web annotation output for provenance reasons. This means you only need that one file as input.

**Comment by kintopp** [comment]
> > Yes, I'll make it a a list:
> > `"lang": [ "nl", "de", "la"]`
> 
> Right, you'll get iso-639-3 from the pipeline, I think @kintopp prefers that for the final web annotations too.

Yes, we're going to use three-letter language codes (iso-639-3) wherever we can in Globalise in place of two-letter ones (iso-639-1).

**Comment by brambg** [comment]
Does the globalise team have a preference for how the lang information should be added to the Page annotation?

For example, for the Page annotation https://annorepo.globalise.huygens.knaw.nl/w3c/globalise-2024-03-18/44f1b698-71fd-4bf7-8414-641655d3b60e
which fields should be added to the `body.metadata` ?

```
"lang": ["nld","fra"],
"langCorrected": false

```

or nested:

```
"languageDetected": {
  "lang": ["nld","fra"],
  "corrected": false
}
```

**Comment by brambg** [comment]
I'm testing the script: 

https://github.com/knaw-huc/globalise-tools/blob/main/scripts/gt-update-annotations.py

on just the `inv_nr=2054` pages, and I'm missing a few pages in `pages.lang.tsv`:

```
inv_nr	page_no
2054	0003
2054	0247
2054	0248
2054	0337
2054	0340
2054	0551
2054	0552
2054	0553
2054	0554
2054	0726
2054	0727
2054	0728
2054	0729
2054	0730 
```

@proycon , can you check why those pages are missing?

**Comment by kintopp** [comment]
Re: what should be in the annotation and whether it should be nested: to my knowledge, "langCorrected" that tells us if someone (i.e. a person) manually overrode an automatic classification. So it should please be included. But as to whether nested or not, this is something Leon wanted to take up with @brambg after he gets back at the end of this month. I suspect it may also be related to whether or not we want to add further page (i.e. scan) level metadata in the future. So perhaps best leave it un-nested for now – but your call. 

Re: missing pages, these may be known issues caused by the NA. I'll run this by Lodewyk Petram now to see if he knows – else, Leon will know.

**Comment by proycon** [comment]
I don't know why those are missing. They might be blank pages? The pageXML for the first one for instance (NL-HaNA_1.04.02_2054_0003.xml) does exist but not not contain any actual text.

**Comment by brambg** [comment]
Some of them are indeed blank, but not all, e.g. NL-HaNA_1.04.02_2054_0726.xml does contain text, even in a paragraph TextRegion

**Comment by proycon** [comment]
I checked a few of those you mentioned, many indeed are blank, so the classification never ran on them since's there nothing.

But I do notice some odd ones like  `2054 0726` which do not appear in the output but do have text.

**Comment by proycon** [comment]
I'm investigating whether this may be a bug in the pipeline, perhaps the last inv_no/page_no was missed.

**Comment by proycon** [comment]
That was a bug indeed, squashed now, I'm running the pipeline again to produce new output.

**Comment by proycon** [comment]
The new output is available in: https://github.com/globalise-huygens/language-identification-data/blob/main/latin-script-pages/pages.lang.tsv

**Comment by brambg** [comment]
The 4486687 records from `pages.lang.tsv` have been used to update the `px:Page` annotations in 

https://transcriptions.globalise.huygens.knaw.nl/

for example, see:

https://transcriptions.globalise.huygens.knaw.nl/detail/urn:globalise:NL-HaNA_1.04.02_9337_0679

Click "Show info", then click the annorepo link to the px:Page annotation:

https://annorepo.globalise.huygens.knaw.nl/w3c/globalise-2024-03-18/698bb2bd-2461-4008-a6b2-8928b7f76a0c

where you can see the added `body.metadata` fields `lang` and `langCorrected`

**Comment by brambg** [comment]
@proycon ,
The last lines of `pages.lang.tsv`:

```
1704	0461	msa	1
1704	0468	msa	1
1704	0469	msa	1
1704	0470	msa	1
1704	0471	msa	1
```

refer to pages that don't have corresponding pagexml files in the 2023-09 batch that's the basis for the current web annotations, are you sure the page ids are correct?

**Comment by proycon** [comment]
Right, well spotted, these come from the manual corrections and it
looks like @kintopp made a typo there?

```
1704    461 msa https://transcriptions.globalise.huygens.knaw.nl/detail/urn:globalise:NL-HaNA_1.04.02_1074_0461 1
1704    468 msa https://transcriptions.globalise.huygens.knaw.nl/detail/urn:globalise:NL-HaNA_1.04.02_1074_0468 1
1704    469 msa https://transcriptions.globalise.huygens.knaw.nl/detail/urn:globalise:NL-HaNA_1.04.02_1074_0469 1
1704    470 msa https://transcriptions.globalise.huygens.knaw.nl/detail/urn:globalise:NL-HaNA_1.04.02_1074_0470 1
1704    471 msa https://transcriptions.globalise.huygens.knaw.nl/detail/urn:globalise:NL-HaNA_1.04.02_1074_0471 1
```
 
Should be 1074 .

**Comment by kintopp** [comment]
Sorry, just getting to this now. Yes, a typo on my part. Inventory 1074 not 1704.

**Comment by kintopp** [comment]
> Does the globalise team have a preference for how the lang information should be added to the Page annotation?
> 
> For example, for the Page annotation https://annorepo.globalise.huygens.knaw.nl/w3c/globalise-2024-03-18/44f1b698-71fd-4bf7-8414-641655d3b60e which fields should be added to the `body.metadata` ?
> 
> ```
> "lang": ["nld","fra"],
> "langCorrected": false
> ```
> 
> or nested:
> 
> ```
> "languageDetected": {
>   "lang": ["nld","fra"],
>   "corrected": false
> }
> ```

@brambg I've reminded Leon to please get back to you with his preferences.
